### Load packages
library(mfp)
library(VGAM)
library(dplyr)
library(Hmisc)
library(rms)
library(ggplot2)
library(Cairo)
library(DescTools)
library(ggpubr)
library(knitr)
library(kernlab)
library(reshape2)