### Load packages
library(dplyr)
library(ggplot2)
library(knitr)
library(boot)
library(rms)
library(pmsampsize)
library(MASS)
library(tidyr)
#library(InformationValue)
library(DescTools)
library(scales)
library(mice)
library(samplesizedev)